### ISSUE TITLE
NaN loss and Watchdog timeout error caused by _accumulate_time_across_ranks

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#70]
Hi, the loss of my training job becomes NaN at step 161544. The job failed due to wathdog timeout error. Looks like the error is caused by this [code](https://github.com/mosaicml/composer/blob/release/v0.14.1/composer/trainer/trainer.py#L1864). Any thoughts? Thanks.

```
2023-10-05T03:29:36.616-07:00 | [0]:train 21%\|█████▏ \| 161543/770000 [29:39:25<397:31:10, 2.35s/ba, loss/train/t[A
-- | --
  | 2023-10-05T03:29:36.616-07:00 | [0]:
  | 2023-10-05T04:00:22.604-07:00 | [0]:train 21%\|█████▏ \| 161544/770000 [29:39:25<310:42:33, 1.84s/ba, loss/train/t[A[6]:[E ProcessGroupNCCL.cpp:828] [Rank 38] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805505 milliseconds before timing out.
  | 2023-10-05T04:00:22.612-07:00 | [1]:[E ProcessGroupNCCL.cpp:828] [Rank 33] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805498 milliseconds before timing out.
  | 2023-10-05T04:00:22.628-07:00 | [7]:[E ProcessGroupNCCL.cpp:828] [Rank 39] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805581 milliseconds before timing out.
  | 2023-10-05T04:00:22.636-07:00 | [3]:[E ProcessGroupNCCL.cpp:828] [Rank 35] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805568 milliseconds before timing out.
  | 2023-10-05T04:00:22.654-07:00 | [5]:[E ProcessGroupNCCL.cpp:828] [Rank 37] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805524 milliseconds before timing out.
  | 2023-10-05T04:00:22.654-07:00 | [5]:Traceback (most recent call last):
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/workspace/mosaic.py", line 28, in <module>
  | 2023-10-05T04:00:22.654-07:00 | [5]: main()
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
  | 2023-10-05T04:00:22.654-07:00 | [5]: return f(*args, **kwargs)
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/workspace/mosaic.py", line 24, in main
  | 2023-10-05T04:00:22.654-07:00 | [5]: return train(cfg)
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/workspace/models/diffusion/train.py", line 170, in train
  | 2023-10-05T04:00:22.654-07:00 | [5]: return eval_and_then_train()
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/workspace/models/diffusion/train.py", line 168, in eval_and_then_train
  | 2023-10-05T04:00:22.654-07:00 | [5]: trainer.fit()
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/opt/conda/lib/python3.9/site-packages/composer/trainer/trainer.py", line 1766, in fit
  | 2023-10-05T04:00:22.654-07:00 | [5]: self._train_loop()
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/opt/conda/lib/python3.9/site-packages/composer/trainer/trainer.py", line 1962, in _train_loop
  | 2023-10-05T04:00:22.654-07:00 | [5]: total_num_samples, total_num_tokens, batch_time = self._accumulate_time_across_ranks(
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/opt/conda/lib/python3.9/site-packages/composer/trainer/trainer.py", line 1864, in _accumulate_time_across_ranks
  | 2023-10-05T04:00:22.654-07:00 | [5]: dist.all_reduce(sample_token_tensor, reduce_operation='SUM')
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/opt/conda/lib/python3.9/site-packages/composer/utils/dist.py", line 212, in all_reduce
  | 2023-10-05T04:00:22.654-07:00 | [5]: dist.all_reduce(tensor, op=reduce_op)
  | 2023-10-05T04:00:22.654-07:00 | [5]: File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
  | 2023-10-05T04:00:22.654-07:00 | [5]: return func(*args, **kwargs)
  | 2023-10-05T04:00:22.654-07:00Copy[5]:  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce | [5]: File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
  | 2023-10-05T04:00:22.654-07:00Copy[5]:    work = default_pg.allreduce([tensor], opts) | [5]: work = default_pg.allreduce([tensor], opts)
  | 2023-10-05T04:00:22.654-07:00 | [5]:RuntimeError: NCCL communicator was aborted on rank 37. Original reason for failure was: [Rank 37] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805524 milliseconds before timing out.
  | 2023-10-05T04:00:22.655-07:00 | [2]:[E ProcessGroupNCCL.cpp:828] [Rank 34] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805579 milliseconds before timing out.
  | 2023-10-05T04:00:22.656-07:00 | [4]:[E ProcessGroupNCCL.cpp:828] [Rank 36] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805597 milliseconds before timing out.
  | 2023-10-05T04:00:22.700-07:00 | [0]:[E ProcessGroupNCCL.cpp:828] [Rank 32] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4447361, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805625 milliseconds before timing out.


```

**Comment by viyjy** [comment]
close it, since the root cause is `botocore.exceptions.NoCredentialsError: Unable to locate credentials during model training`
